server:
  port: 8082
  netty:
    event-loop-threads: 0
    connection-timeout: 10000
    idle-timeout: 60000

spring:
  application:
    name: order-service
  codec:
    max-in-memory-size: 10MB

service:
  latency:
    min-ms: 10
    max-ms: 100
  error-rate: 0.0

spring.threads:
  virtual:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.sgp.order: INFO
    reactor.netty: WARN
